# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Cédric Dangeard
title: Étudiant en mathématiques appliquées, Statistique
email: cedric@dangeard.fr
#website:

# Social links
#twitter_username:
github_username:  cdangeard
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username:
linkedin_username: cdangeard
# pinterest_username:
#youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Cédric and I'm a student in data science. I'm actualy looking for a internship, so if you are looking for a passionate and curious student to fill a place, feel free to contact me.

  I am most skilled in: <mark>Machine Learning</mark>, <mark>Python</mark> and <mark>Reading board games rules</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in neural networks and AI some of my other interests and hobbies are:
   - [Ultimate frisbee](https://www.youtube.com/watch?v=Yqwgk6Pg1AA)
   - Board Games
   - Gaming
   - History
   - Traveling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
